# Generated by Django 4.0.4 on 2022-04-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_alter_block_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='counted',
            field=models.BooleanField(default=False),
        ),
    ]
